GET http://127.0.0.1/api/v1/jobs
Accept: application/json
Content-Type: application/json

# _token=w7f5xAw3sygmurgFAEMfrQwejPOVD7t1X9RzU0SC&name=test&email=test%40testdomain.com&password=test&submit=Register
